const heading = document.getElementById('main-heading')
heading.innerHTML = 'Fruit World'
heading.style.color = 'orange'
const header = document.getElementById('header')
header.style.backgroundColor = 'green'
header.style.borderBottom = '2px solid orange'
const fruitHeading = document.getElementById('basket-heading')
fruitHeading.style.color='green'
const thanks = document.getElementById('thanks')
thanks.innerHTML = "<p>Please visit us again</p>"